#!/usr/bin/env python3
"""Export supported SDF visual geometry to the replay's checked-in scene data."""
import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]


def numbers(element, path, default):
    return [float(v) for v in element.findtext(path, default).split()]


def export_world(path):
    world = ET.parse(path).getroot().find('world')
    result = {'name': world.get('name'), 'background': numbers(world, 'scene/background', '0.48 0.68 0.88 1'),
              'ambient': numbers(world, 'scene/ambient', '0.72 0.76 0.82 1'),
              'fog': {'color': numbers(world, 'scene/fog/color', '0.72 0.80 0.88 1'),
                      'start': float(world.findtext('scene/fog/start', '140')),
                      'end': float(world.findtext('scene/fog/end', '300'))},
              'models': [], 'obstacles': []}
    for model in world.findall('model'):
        item = {'name': model.get('name'), 'pose': numbers(model, 'pose', '0 0 0 0 0 0'), 'links': []}
        for link in model.findall('link'):
            entry = {'pose': numbers(link, 'pose', '0 0 0 0 0 0'), 'visuals': []}
            for visual in link.findall('visual'):
                geometry = visual.find('geometry')[0]
                if geometry.tag not in ('box', 'sphere', 'cylinder', 'plane'):
                    raise ValueError(f'Unsupported visual: {geometry.tag}')
                entry['visuals'].append({
                    'name': visual.get('name'), 'pose': numbers(visual, 'pose', '0 0 0 0 0 0'),
                    'geometry': {'type': geometry.tag, **{child.tag: [float(v) for v in child.text.split()] for child in geometry}},
                    'color': numbers(visual, 'material/diffuse', '0.7 0.7 0.7 1'),
                    'emissive': numbers(visual, 'material/emissive', '0 0 0 1'),
                    'transparency': float(visual.findtext('transparency', '0')),
                    'castShadows': visual.findtext('cast_shadows', 'true') == 'true',
                })
            item['links'].append(entry)
        result['models'].append(item)
        if item['name'].startswith('obstacle_'):
            visuals = item['links'][0]['visuals']
            body, roof = visuals
            e, n, _ = body['geometry']['size']
            re, rn, rh = roof['geometry']['size']
            result['obstacles'].append({'name': 'OB' + item['name'].split('_')[-1],
                'east': item['pose'][0], 'north': item['pose'][1], 'sizeE': e, 'sizeN': n,
                'h': body['geometry']['size'][2], 'color': body['color'][:3],
                'roof': {'sizeE': re, 'sizeN': rn, 'h': rh, 'color': roof['color'][:3]}})
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'web/replay/gazebo-world.js'
    text = '// Generated by scripts/export_gazebo_world.py; edit worlds/obstacle_world.sdf.\nconst GAZEBO_WORLD = ' + json.dumps(export_world(ROOT / 'worlds/obstacle_world.sdf'), indent=2) + ';\nif (typeof module !== "undefined") module.exports = GAZEBO_WORLD;\n'
    if args.check:
        if not output.exists() or output.read_text() != text:
            raise SystemExit('Gazebo web scene is stale; run scripts/export_gazebo_world.py')
    else:
        output.write_text(text)


if __name__ == '__main__':
    main()
