#!/usr/bin/env python3
"""Generate the search-and-find world: an open field with ArUco targets on the ground.

Writes (all deterministic from the constants below):
  worlds/search_field.sdf                    the Gazebo world
  worlds/search_field_targets.json           ground truth -- for the verifier only, never the drones
  models/aruco_marker_<id>/                  one textured model per target

    python tools/gen_search_world.py           # (re)generate
    python tools/gen_search_world.py --check   # exit 1 if committed files are stale

Frames: the truth file uses NED from the spawn point (north, east), like the rest of the
mission code. Gazebo's world frame is ENU, so a target at (north, east) is placed at
pose x=east, y=north.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import tempfile
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]

WORLD_NAME = "search_field"
DICTIONARY = "DICT_4X4_50"
SEED = 7
N_TARGETS = 8
# Search area, NED metres from spawn. 60 x 60 m: room for ten drones' lanes.
FIELD = {"north_min": 0.0, "north_max": 60.0, "east_min": -30.0, "east_max": 30.0}
EDGE_MARGIN_M = 4.0
LAUNCH_STRIP_NORTH_MAX_M = 10.0  # homes live south of this; no targets there
MIN_SPACING_M = 8.0
MARKER_LENGTH_M = 1.0  # side of the black ArUco square, as the detector measures it
CELL_PX = 40           # texture pixels per ArUco cell (4x4 bits + 1-bit border = 6 cells)
QUIET_PX = 40          # white margin around the marker: detection needs contrast at the edge
GROUND_Z_M = 0.01      # just above the ground plane, to avoid z-fighting


def _targets() -> list[dict]:
    rng = random.Random(SEED)
    ids = sorted(rng.sample(range(50), N_TARGETS))
    placed: list[dict] = []
    while len(placed) < N_TARGETS:
        n = round(rng.uniform(max(FIELD["north_min"] + EDGE_MARGIN_M, LAUNCH_STRIP_NORTH_MAX_M),
                              FIELD["north_max"] - EDGE_MARGIN_M), 2)
        e = round(rng.uniform(FIELD["east_min"] + EDGE_MARGIN_M, FIELD["east_max"] - EDGE_MARGIN_M), 2)
        if all(((n - p["north"]) ** 2 + (e - p["east"]) ** 2) ** 0.5 >= MIN_SPACING_M for p in placed):
            placed.append({"id": ids[len(placed)], "north": n, "east": e})
    return placed


def _marker_image(marker_id: int) -> np.ndarray:
    dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, DICTIONARY))
    side = CELL_PX * 6
    if hasattr(cv2.aruco, "generateImageMarker"):
        img = cv2.aruco.generateImageMarker(dictionary, marker_id, side)
    else:  # OpenCV < 4.7
        img = cv2.aruco.drawMarker(dictionary, marker_id, side)
    return cv2.copyMakeBorder(img, QUIET_PX, QUIET_PX, QUIET_PX, QUIET_PX, cv2.BORDER_CONSTANT, value=255)


def _plane_size_m() -> float:
    side_px = CELL_PX * 6
    return round(MARKER_LENGTH_M * (side_px + 2 * QUIET_PX) / side_px, 6)


def _model_sdf(marker_id: int) -> str:
    size = _plane_size_m()
    return f"""<?xml version="1.0" ?>
<!-- Generated by tools/gen_search_world.py: ArUco {DICTIONARY} id {marker_id}, {MARKER_LENGTH_M} m marker. -->
<sdf version="1.9">
  <model name="aruco_marker_{marker_id}">
    <static>true</static>
    <link name="link">
      <visual name="visual">
        <cast_shadows>false</cast_shadows>
        <geometry><plane><normal>0 0 1</normal><size>{size} {size}</size></plane></geometry>
        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr><metal>
            <albedo_map>model://aruco_marker_{marker_id}/materials/textures/aruco_{marker_id}.png</albedo_map>
            <roughness>1.0</roughness>
            <metalness>0.0</metalness>
          </metal></pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""


def _model_config(marker_id: int) -> str:
    return f"""<?xml version="1.0"?>
<model>
  <name>aruco_marker_{marker_id}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>Search target: ArUco {DICTIONARY} id {marker_id} on the ground. Generated by tools/gen_search_world.py.</description>
</model>
"""


def _boundary_strips() -> str:
    """Thin white strips outlining the search area (visual only)."""
    f = FIELD
    width_e, length_n = f["east_max"] - f["east_min"], f["north_max"] - f["north_min"]
    mid_e, mid_n = (f["east_max"] + f["east_min"]) / 2, (f["north_max"] + f["north_min"]) / 2
    strips = [  # (x=east, y=north, size_x, size_y)
        (mid_e, f["north_min"], width_e, 0.3), (mid_e, f["north_max"], width_e, 0.3),
        (f["east_min"], mid_n, 0.3, length_n), (f["east_max"], mid_n, 0.3, length_n),
    ]
    visuals = "\n".join(
        f"""        <visual name="edge_{i}">
          <pose>{x} {y} 0.005 0 0 0</pose>
          <geometry><box><size>{sx} {sy} 0.01</size></box></geometry>
          <material><ambient>0.95 0.95 0.95 1</ambient><diffuse>0.95 0.95 0.95 1</diffuse></material>
        </visual>""" for i, (x, y, sx, sy) in enumerate(strips))
    return f"""    <model name="search_area_outline">
      <static>true</static>
      <link name="link">
{visuals}
      </link>
    </model>"""


def _world_sdf(targets: list[dict]) -> str:
    includes = "\n".join(
        f"""    <include>
      <uri>model://aruco_marker_{t['id']}</uri>
      <name>target_{t['id']}</name>
      <pose>{t['east']} {t['north']} {GROUND_Z_M} 0 0 0</pose>
    </include>""" for t in targets)
    return f"""<?xml version="1.0" ?>
<!--
  GENERATED by tools/gen_search_world.py. Do not edit by hand; change the generator.

  Search-and-find field: {int(FIELD['north_max'] - FIELD['north_min'])} x {int(FIELD['east_max'] - FIELD['east_min'])} m of open ground with {N_TARGETS} ArUco
  ({DICTIONARY}, {MARKER_LENGTH_M} m) targets. Ground truth for scoring: search_field_targets.json
  (the verifier reads it; flight code must not). Gazebo frame is ENU: x=east, y=north.

  Physics, scene, GPS origin and lighting match obstacle_world.sdf. As there, NO plugin
  declarations: PX4's server.config provides every world system plugin.

  Usage: PX4_GZ_WORLD={WORLD_NAME} make px4_sitl gz_x500  (with models/ and worlds/ on
  GZ_SIM_RESOURCE_PATH, as full_stack.launch.py sets up)
-->
<sdf version="1.9">
  <world name="{WORLD_NAME}">

    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <scene>
      <ambient>0.72 0.76 0.82 1</ambient>
      <background>0.48 0.68 0.88 1</background>
      <sky/>
    </scene>

    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <latitude_deg>47.397742</latitude_deg>
      <longitude_deg>8.545594</longitude_deg>
      <elevation>488.0</elevation>
      <heading_deg>0</heading_deg>
    </spherical_coordinates>

    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>1.0 1.0 1.0 1</diffuse>
      <specular>0.4 0.4 0.4 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>300 300</size></plane></geometry>
          <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry><plane><normal>0 0 1</normal><size>300 300</size></plane></geometry>
          <material>
            <ambient>0.45 0.62 0.37 1</ambient>
            <diffuse>0.45 0.62 0.37 1</diffuse>
            <specular>0.05 0.05 0.05 1</specular>
          </material>
        </visual>
      </link>
    </model>

{_boundary_strips()}

{includes}

  </world>
</sdf>
"""


def _truth(targets: list[dict]) -> str:
    doc = {
        "world": WORLD_NAME,
        "frame": "NED metres from the spawn point (north, east)",
        "dictionary": DICTIONARY,
        "marker_length_m": MARKER_LENGTH_M,
        "field": FIELD,
        "placement": {"seed": SEED, "edge_margin_m": EDGE_MARGIN_M,
                      "launch_strip_north_max_m": LAUNCH_STRIP_NORTH_MAX_M, "min_spacing_m": MIN_SPACING_M},
        "note": "Ground truth for scoring search results. Flight code must not read this file.",
        "targets": targets,
    }
    return json.dumps(doc, indent=2) + "\n"


def _write(root: Path) -> list[Path]:
    targets = _targets()
    written = []

    def put(rel: str, content) -> None:
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, np.ndarray):
            cv2.imwrite(str(path), content)
        else:
            path.write_text(content)
        written.append(Path(rel))

    put(f"worlds/{WORLD_NAME}.sdf", _world_sdf(targets))
    put(f"worlds/{WORLD_NAME}_targets.json", _truth(targets))
    for t in targets:
        m = t["id"]
        put(f"models/aruco_marker_{m}/model.sdf", _model_sdf(m))
        put(f"models/aruco_marker_{m}/model.config", _model_config(m))
        put(f"models/aruco_marker_{m}/materials/textures/aruco_{m}.png", _marker_image(m))
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed files are stale")
    args = parser.parse_args()
    if not args.check:
        for rel in _write(ROOT):
            print(f"wrote {rel}")
        return 0
    stale = []
    with tempfile.TemporaryDirectory() as tmp:
        for rel in _write(Path(tmp)):
            fresh, committed = Path(tmp) / rel, ROOT / rel
            if not committed.exists():
                stale.append(f"missing: {rel}")
            elif rel.suffix == ".png":  # compare pixels: PNG bytes vary between OpenCV builds
                a = cv2.imread(str(fresh), cv2.IMREAD_GRAYSCALE)
                b = cv2.imread(str(committed), cv2.IMREAD_GRAYSCALE)
                if b is None or a.shape != b.shape or not np.array_equal(a, b):
                    stale.append(f"differs: {rel}")
            elif fresh.read_text() != committed.read_text():
                stale.append(f"differs: {rel}")
    for line in stale:
        print(line)
    if stale:
        print("search world is stale: run python tools/gen_search_world.py", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
