// Generated by scripts/export_gazebo_world.py; edit worlds/obstacle_world.sdf.
const GAZEBO_WORLD = {
  "name": "obstacle_world",
  "background": [
    0.48,
    0.68,
    0.88,
    1.0
  ],
  "ambient": [
    0.72,
    0.76,
    0.82,
    1.0
  ],
  "fog": {
    "color": [
      0.72,
      0.8,
      0.88,
      1.0
    ],
    "start": 140.0,
    "end": 300.0
  },
  "models": [
    {
      "name": "ground_plane",
      "pose": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "plane",
                "normal": [
                  0.0,
                  0.0,
                  1.0
                ],
                "size": [
                  300.0,
                  300.0
                ]
              },
              "color": [
                0.45,
                0.62,
                0.37,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            }
          ]
        }
      ]
    },
    {
      "name": "training_course",
      "pose": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "course_surface",
              "pose": [
                0.0,
                25.0,
                0.012,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  36.0,
                  60.0,
                  0.02
                ]
              },
              "color": [
                0.24,
                0.29,
                0.31,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "boundary_west",
              "pose": [
                -18.0,
                25.0,
                0.03,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.18,
                  60.0,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.82,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "boundary_east",
              "pose": [
                18.0,
                25.0,
                0.03,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.18,
                  60.0,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.82,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_e_m10",
              "pose": [
                -10.0,
                25.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.055,
                  60.0,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_e_m5",
              "pose": [
                -5.0,
                25.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.055,
                  60.0,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_e_0",
              "pose": [
                0.0,
                25.0,
                0.029,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.12,
                  60.0,
                  0.024
                ]
              },
              "color": [
                0.88,
                0.9,
                0.92,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_e_5",
              "pose": [
                5.0,
                25.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.055,
                  60.0,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_e_10",
              "pose": [
                10.0,
                25.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.055,
                  60.0,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_5",
              "pose": [
                0.0,
                5.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_10",
              "pose": [
                0.0,
                10.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_15",
              "pose": [
                0.0,
                15.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_20",
              "pose": [
                0.0,
                20.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_25",
              "pose": [
                0.0,
                25.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_30",
              "pose": [
                0.0,
                30.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_35",
              "pose": [
                0.0,
                35.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_40",
              "pose": [
                0.0,
                40.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_45",
              "pose": [
                0.0,
                45.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "grid_n_50",
              "pose": [
                0.0,
                50.0,
                0.028,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  30.0,
                  0.055,
                  0.022
                ]
              },
              "color": [
                0.55,
                0.61,
                0.63,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_pad",
              "pose": [
                -3.0,
                0.0,
                0.045,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  2.5
                ],
                "length": [
                  0.035
                ]
              },
              "color": [
                0.08,
                0.1,
                0.12,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h_crossbar",
              "pose": [
                -3.0,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  1.7,
                  0.28,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h_left",
              "pose": [
                -3.7,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h_right",
              "pose": [
                -2.3,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_pad_2",
              "pose": [
                7.0,
                0.0,
                0.045,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  2.5
                ],
                "length": [
                  0.035
                ]
              },
              "color": [
                0.08,
                0.1,
                0.12,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h2_crossbar",
              "pose": [
                7.0,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  1.7,
                  0.28,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h2_left",
              "pose": [
                6.3,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "launch_h2_right",
              "pose": [
                7.7,
                0.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.95,
                0.95,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "landing_pad",
              "pose": [
                0.0,
                50.0,
                0.045,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  2.5
                ],
                "length": [
                  0.035
                ]
              },
              "color": [
                0.08,
                0.1,
                0.12,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "landing_ring",
              "pose": [
                0.0,
                50.0,
                0.055,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  2.72
                ],
                "length": [
                  0.012
                ]
              },
              "color": [
                0.95,
                0.72,
                0.08,
                1.0
              ],
              "emissive": [
                0.35,
                0.22,
                0.02,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "landing_h_crossbar",
              "pose": [
                0.0,
                50.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  1.7,
                  0.28,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.82,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "landing_h_left",
              "pose": [
                -0.7,
                50.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.82,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            },
            {
              "name": "landing_h_right",
              "pose": [
                0.7,
                50.0,
                0.07,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.28,
                  1.8,
                  0.025
                ]
              },
              "color": [
                0.95,
                0.82,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": false
            }
          ]
        }
      ]
    },
    {
      "name": "course_beacons",
      "pose": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "west_10",
              "pose": [
                -16.0,
                10.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "east_10",
              "pose": [
                16.0,
                10.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "west_25",
              "pose": [
                -16.0,
                25.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "east_25",
              "pose": [
                16.0,
                25.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "west_40",
              "pose": [
                -16.0,
                40.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "east_40",
              "pose": [
                16.0,
                40.0,
                0.65,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.18
                ],
                "length": [
                  1.3
                ]
              },
              "color": [
                1.0,
                0.35,
                0.02,
                1.0
              ],
              "emissive": [
                0.3,
                0.08,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "obstacle_1",
      "pose": [
        -6.0,
        10.0,
        5.75,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  3.0,
                  3.0,
                  11.5
                ]
              },
              "color": [
                0.85,
                0.15,
                0.15,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "roof_marker",
              "pose": [
                0.0,
                0.0,
                5.45,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  3.18,
                  3.18,
                  0.12
                ]
              },
              "color": [
                0.08,
                0.08,
                0.08,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "obstacle_2",
      "pose": [
        10.0,
        10.0,
        3.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  3.0,
                  3.0,
                  6.0
                ]
              },
              "color": [
                0.9,
                0.5,
                0.05,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "roof_marker",
              "pose": [
                0.0,
                0.0,
                2.03,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  4.18,
                  3.18,
                  0.12
                ]
              },
              "color": [
                0.98,
                0.98,
                0.98,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "obstacle_3",
      "pose": [
        -8.0,
        24.0,
        2.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  5.0,
                  3.0,
                  4.0
                ]
              },
              "color": [
                0.15,
                0.65,
                0.15,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "roof_marker",
              "pose": [
                0.0,
                0.0,
                2.53,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  2.18,
                  2.18,
                  0.12
                ]
              },
              "color": [
                0.98,
                0.98,
                0.98,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "obstacle_4",
      "pose": [
        6.0,
        24.0,
        2.5,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  3.0,
                  2.0,
                  5.0
                ]
              },
              "color": [
                0.15,
                0.15,
                0.85,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "roof_marker",
              "pose": [
                0.0,
                0.0,
                2.53,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  2.18,
                  2.18,
                  0.12
                ]
              },
              "color": [
                0.98,
                0.98,
                0.98,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "obstacle_5",
      "pose": [
        0.0,
        38.0,
        5.75,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "visual",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  5.0,
                  3.0,
                  11.5
                ]
              },
              "color": [
                0.65,
                0.0,
                0.75,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "roof_marker",
              "pose": [
                0.0,
                0.0,
                5.45,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  5.18,
                  3.18,
                  0.12
                ]
              },
              "color": [
                0.08,
                0.08,
                0.08,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "gps_denied_zone",
      "pose": [
        0.0,
        23.5,
        6.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "volume",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  16.0,
                  16.0,
                  12.0
                ]
              },
              "color": [
                0.15,
                0.85,
                1.0,
                0.18
              ],
              "emissive": [
                0.03,
                0.16,
                0.2,
                1.0
              ],
              "transparency": 0.82,
              "castShadows": true
            },
            {
              "name": "outline",
              "pose": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  16.18,
                  16.18,
                  12.18
                ]
              },
              "color": [
                0.1,
                0.95,
                1.0,
                0.38
              ],
              "emissive": [
                0.04,
                0.22,
                0.24,
                1.0
              ],
              "transparency": 0.62,
              "castShadows": true
            }
          ]
        }
      ]
    },
    {
      "name": "landscape_landmarks",
      "pose": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "links": [
        {
          "pose": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
          ],
          "visuals": [
            {
              "name": "tree_w1_trunk",
              "pose": [
                -28.0,
                8.0,
                1.1,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.35
                ],
                "length": [
                  2.2
                ]
              },
              "color": [
                0.3,
                0.16,
                0.07,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_w1_crown",
              "pose": [
                -28.0,
                8.0,
                3.0,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "sphere",
                "radius": [
                  1.8
                ]
              },
              "color": [
                0.12,
                0.38,
                0.12,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_w2_trunk",
              "pose": [
                -25.0,
                31.0,
                1.3,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.4
                ],
                "length": [
                  2.6
                ]
              },
              "color": [
                0.3,
                0.16,
                0.07,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_w2_crown",
              "pose": [
                -25.0,
                31.0,
                3.5,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "sphere",
                "radius": [
                  2.1
                ]
              },
              "color": [
                0.1,
                0.34,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_e1_trunk",
              "pose": [
                27.0,
                18.0,
                1.2,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.38
                ],
                "length": [
                  2.4
                ]
              },
              "color": [
                0.3,
                0.16,
                0.07,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_e1_crown",
              "pose": [
                27.0,
                18.0,
                3.2,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "sphere",
                "radius": [
                  1.9
                ]
              },
              "color": [
                0.13,
                0.4,
                0.13,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_e2_trunk",
              "pose": [
                30.0,
                43.0,
                1.35,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "cylinder",
                "radius": [
                  0.42
                ],
                "length": [
                  2.7
                ]
              },
              "color": [
                0.3,
                0.16,
                0.07,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "tree_e2_crown",
              "pose": [
                30.0,
                43.0,
                3.6,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "sphere",
                "radius": [
                  2.2
                ]
              },
              "color": [
                0.1,
                0.35,
                0.1,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "shelter",
              "pose": [
                22.0,
                -2.0,
                1.5,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  7.0,
                  5.0,
                  3.0
                ]
              },
              "color": [
                0.48,
                0.5,
                0.52,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "shelter_roof",
              "pose": [
                22.0,
                -2.0,
                3.15,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  7.5,
                  5.5,
                  0.3
                ]
              },
              "color": [
                0.16,
                0.18,
                0.2,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            },
            {
              "name": "shelter_window",
              "pose": [
                18.49,
                -2.0,
                1.7,
                0.0,
                0.0,
                0.0
              ],
              "geometry": {
                "type": "box",
                "size": [
                  0.03,
                  2.3,
                  1.1
                ]
              },
              "color": [
                0.08,
                0.32,
                0.5,
                1.0
              ],
              "emissive": [
                0.0,
                0.0,
                0.0,
                1.0
              ],
              "transparency": 0.0,
              "castShadows": true
            }
          ]
        }
      ]
    }
  ],
  "obstacles": [
    {
      "name": "OB1",
      "east": -6.0,
      "north": 10.0,
      "sizeE": 3.0,
      "sizeN": 3.0,
      "h": 11.5,
      "color": [
        0.85,
        0.15,
        0.15
      ],
      "roof": {
        "sizeE": 3.18,
        "sizeN": 3.18,
        "h": 0.12,
        "color": [
          0.08,
          0.08,
          0.08
        ]
      }
    },
    {
      "name": "OB2",
      "east": 10.0,
      "north": 10.0,
      "sizeE": 3.0,
      "sizeN": 3.0,
      "h": 6.0,
      "color": [
        0.9,
        0.5,
        0.05
      ],
      "roof": {
        "sizeE": 4.18,
        "sizeN": 3.18,
        "h": 0.12,
        "color": [
          0.98,
          0.98,
          0.98
        ]
      }
    },
    {
      "name": "OB3",
      "east": -8.0,
      "north": 24.0,
      "sizeE": 5.0,
      "sizeN": 3.0,
      "h": 4.0,
      "color": [
        0.15,
        0.65,
        0.15
      ],
      "roof": {
        "sizeE": 2.18,
        "sizeN": 2.18,
        "h": 0.12,
        "color": [
          0.98,
          0.98,
          0.98
        ]
      }
    },
    {
      "name": "OB4",
      "east": 6.0,
      "north": 24.0,
      "sizeE": 3.0,
      "sizeN": 2.0,
      "h": 5.0,
      "color": [
        0.15,
        0.15,
        0.85
      ],
      "roof": {
        "sizeE": 2.18,
        "sizeN": 2.18,
        "h": 0.12,
        "color": [
          0.98,
          0.98,
          0.98
        ]
      }
    },
    {
      "name": "OB5",
      "east": 0.0,
      "north": 38.0,
      "sizeE": 5.0,
      "sizeN": 3.0,
      "h": 11.5,
      "color": [
        0.65,
        0.0,
        0.75
      ],
      "roof": {
        "sizeE": 5.18,
        "sizeN": 3.18,
        "h": 0.12,
        "color": [
          0.08,
          0.08,
          0.08
        ]
      }
    }
  ]
};
if (typeof module !== "undefined") module.exports = GAZEBO_WORLD;
